version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docs:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auto.rule=Host(`auto.wuhanstudio.uk`)"
        - "traefik.http.routers.auto.entrypoints=web"
        - "traefik.http.services.auto.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.autos.rule=Host(`auto.wuhanstudio.uk`)"
        - "traefik.http.routers.autos.entrypoints=websecure"
        - "traefik.http.routers.autos.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.auto.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
